### ISSUE TITLE
PermissionError: [WinError 32]    logs/log_20240906_015721.log

### ISSUE THREAD

**Issue by wells-77** [aravind-selvam/video-transcript-summarizer#4]
Hi there,

I encountered an issue while running the project where the app is unable to access or delete the log files due to a PermissionError: [WinError 32]. It seems another process is using the log file, preventing my application from proceeding. I've tried restarting and even deleting the file manually, but it gets recreated, leading to the same conflict.

Do you have any suggestions on how to resolve this issue or any changes I can make to avoid the log file being locked?

Thanks for your help!

**Comment by aravind-selvam** [comment]
Hi, please try removing the logger itself and running the code. Alternatively, you can remove the part:
```
if os.path.exists(LOG_DIR):
    shutil.rmtree(LOG_DIR)
os.makedirs(LOG_DIR, exist_ok=True)
```
Since this is an old project that I’m no longer using or maintaining, kindly check by following the above steps and let me know how it works.

**Comment by wells-77** [comment]
Thank you for your response. I have already achieved my goal through other means, but I greatly appreciate your assistance.
